[project]
name = ""
version = ""
description = ""
authors = [
    {name = "wbchen", email = "wbchen@bigquant.ai"},
]
dependencies = [
    "pandas>=2.2.1",
    "numpy>=1.26.4",
]
requires-python = ">=3.10"
readme = "README.md"
license = {text = "MIT"}

